#---------------------------
#Github action by Andrew Semenyuk
#--------------------------
name: my_GitHub_Action
env:
  App_NAME : "MY N"
  PACK_NAME: "test action vers-${{github.sha}}"
  

on:
  push:
    branches:
      - main

jobs:
  my_test:

    runs-on: ubuntu-latest

    steps:
    - name: Print Hello mass
      run: echo "Hello world! from testing"
    
    - name: new commands
      run: |
        echo "Hello mass1"
        echo "Hello mass2"
        echo "App name is: ${{env.App_NAME}}"
    
    - name: list curr folder
      run: ls -la

    - name: git clone this rep
      uses: actions/checkout@v1
    
    - name: list curr folder
      run: ls -la

  my_dep:

    runs-on: ubuntu-latest
    needs: [my_test]
    env:
      var1: "Job1"
      var2: "Job2"
      
    steps:
    - name: Hello by dep
      run: echo "Hello world by dep"

    - name: print dep_pack
      run: echo "Pack name is ${{env.PACK_NAME}}"

    - name: print local envs
      run: |
        echo "var1 = ${{env.var1}}"
        echo "var2 = ${{env.var2}}"
        echo "Local var = $Local_var"
      env:
        Local_var: "Mega loca"
        
    - name: last vers AWS
      run: aws --version

    - name: vers zip
      run: zip --version
      
    
    
